### ISSUE TITLE
Disable close dialog by back button option

### ISSUE THREAD

**Issue by dennbagas** [fayaz07/progress_dialog#10]
I know there is an option to `barrierDismissible`, but it only prevents tap on the screen, if the back button got tapped, the dialog is closed. Is there any option that makes back button disabled when the dialog show up? Btw this plugin is really awesome :)

**Comment by fayaz07** [comment]
Thank you @dennbagas, surely I would look into your request.

**Comment by chinachance** [comment]
i have same idea

**Comment by dennbagas** [comment]
I proposed a pull request for this issue, please review it

**Comment by fayaz07** [comment]
sorry @dennbagas actually I was out of station, I will do it asap

**Comment by fayaz07** [comment]
I have fixed the issue in latest update pub v1.2.0, library will be updated soon, thank you!
