### ISSUE TITLE
Crash when calling update method

### ISSUE THREAD

**Issue by fg2q1q3q** [fayaz07/progress_dialog#17]
First of all, thank you for your contribution.

Calling the` update `method immediately after the` show `method is called will crash, although it may not be very common to use it like me, but you should deal with this bug.

**Comment by fayaz07** [comment]
Yeah sure @fg2q1q3q

**Comment by fayaz07** [comment]
Fixed in latest update pub v1.2.0, update will be published soon! Thank you!
