### ISSUE TITLE
When changing Page, progress is closed instead of page change

### ISSUE THREAD

**Issue by boskokg** [fayaz07/progress_dialog#18]
I had a scenario where I forgot to close the progress dialog before navigating to a different page.
Instead of changing a page, Navigator only closed the progress dialog.

Since I have a big project where this issue can happen again I cannot let this behavior happen again.

Sorry, but I had to use a different progress dialog plugin.

Note: I am writing this so others know what they must be aware of with the current implementation of the plugin.

**Comment by fayaz07** [comment]
In my case I didn't face any issue as you have encountered the page properly navigated and even the dialog got closed properly.
Anyhow I will check it again, work on your request, thank you for reporting!

**Comment by fayaz07** [comment]
@boskokg considering this issue, it happens when page is routed to other without closing the dialog, so it looks for disposing the widget, I have added a check for it when the widget is disposed, hope that works, please checkout the latest update pub v1.2.0 will be released soon, thank you!

**Comment by fayaz07** [comment]
Hi @boskokg , please do checkout the latest version of library, that would definitely help solve the issue you faced. I would be pleased if you check out and close the isssue if it resolved your problem!
