### ISSUE TITLE
Because flutter_app depends on progress_dialog ^1.2.0 which doesn't match any versions

### ISSUE THREAD

**Issue by HyggeBo7** [fayaz07/progress_dialog#21]
Because flutter_app depends on progress_dialog ^1.2.0 which doesn't match any versions, version solving failed.
pub get failed (1)

flutter sdk:
 channel:beta
version: v1.9.1+hotfix.2

**Comment by fayaz07** [comment]
Hi @DearBo7, please note that latest published version is 1.1.0+1, version: 1.2.0 will be published soon after prior testing. Thank you!

**Comment by fayaz07** [comment]
Update is live now! Check it out.
