### ISSUE TITLE
update after show causes widget not mounted crash

### ISSUE THREAD

**Issue by zmabies** [fayaz07/progress_dialog#29]
**Using update method after show method causes the following crash error:**
_Unhandled Exception: setState() called in constructor: (lifecycle state: created, no widget, not mounted) This happens when you call setState() on a State object for a widget that hasn't been inserted into the widget tree yet. It is not necessary to call setState() in the constructor, since the state is already assumed to be dirty when it is initially created._

**To Reproduce**
1. declare ProgressDialog and initialize in build
2. show dialog
3. update dialog
4. hide dialog
5. repeat steps 2-4 until it crashes

**Comment by tiagooliveira1** [comment]
Me too.

**Comment by fayaz07** [comment]
Hi, can you post sample code which I can use to test.

**Comment by zmabies** [comment]
Hello @fayaz07 

please see this repo for the code: 
https://github.com/zmabies/ProgressDialogTest

**Comment by fayaz07** [comment]
Launching lib/main.dart on SM J600G in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device SM J600G...
D/InputMethodManager( 7540): prepareNavigationBarInfo() DecorView@4f0f7d4[MainActivity]
D/InputMethodManager( 7540): getNavigationBarColor() -855310
V/InputMethodManager( 7540): Starting input: tba=com.fayaz07.counter_bloc ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 7540): startInputInner - Id : 0
I/InputMethodManager( 7540): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 7540): Input channel constructed: fd=92
D/InputTransport( 7540): Input channel destroyed: fd=89
D/ViewRootImpl@f24af35[MainActivity]( 7540): stopped(true) old=false
D/SurfaceView( 7540): windowStopped(true) false io.flutter.view.FlutterView{97ff458 VFE...... ........ 0,0-720,1396} of ViewRootImpl@f24af35[MainActivity]
D/SurfaceView( 7540): show() Surface(name=SurfaceView - com.fayaz07.counter_bloc/com.fayaz07.counter_bloc.MainActivity@97ff458@0[7540])/@0xbfe09b1 io.flutter.view.FlutterView{97ff458 VFE...... ........ 0,0-720,1396}
D/SurfaceView( 7540): surfaceDestroyed callback.size 1 #1 io.flutter.view.FlutterView{97ff458 VFE...... ........ 0,0-720,1396}
W/libEGL  ( 7540): EGLNativeWindowType 0xe6be8008 disconnect failed
D/SurfaceView( 7540): destroy() Surface(name=SurfaceView - com.fayaz07.counter_bloc/com.fayaz07.counter_bloc.MainActivity@97ff458@0[7540])/@0xbfe09b1 io.flutter.view.FlutterView{97ff458 VFE...... ........ 0,0-720,1396}
D/ViewRootImpl@f24af35[MainActivity]( 7540): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 7540): prepareNavigationBarInfo() DecorView@4f0f7d4[MainActivity]
D/InputMethodManager( 7540): getNavigationBarColor() -855310
D/SurfaceView( 7540): onWindowVisibilityChanged(8) false io.flutter.view.FlutterView{97ff458 VFE...... ........ 0,0-720,1396} of ViewRootImpl@f24af35[MainActivity]
W/libEGL  ( 7540): EGLNativeWindowType 0xd3b7f808 disconnect failed
D/OpenGLRenderer( 7540): eglDestroySurface = 0xceafc300, 0xd3b7f800
D/ViewRootImpl@f24af35[MainActivity]( 7540): Relayout returned: old=[0,0][720,1480] new=[0,0][720,1480] result=0x5 surface={false 0} changed=false
D/ViewRootImpl@f24af35[MainActivity]( 7540): stopped(false) old=true
D/SurfaceView( 7540): windowStopped(false) false io.flutter.view.FlutterView{97ff458 VFE...... ........ 0,0-720,1396} of ViewRootImpl@f24af35[MainActivity]
D/SurfaceView( 7540): onWindowVisibilityChanged(0) true io.flutter.view.FlutterView{97ff458 VFE...... ........ 0,0-720,1396} of ViewRootImpl@f24af35[MainActivity]
D/ViewRootImpl@f24af35[MainActivity]( 7540): Relayout returned: old=[0,0][720,1480] new=[0,0][720,1480] result=0x7 surface={true 3871244288} changed=true
D/mali_winsys( 7540): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000,  [720x1480]-format:1
D/OpenGLRenderer( 7540): eglCreateWindowSurface = 0xceafc300, 0xe6be8008
D/SurfaceView( 7540): show() Surface(name=SurfaceView - com.fayaz07.counter_bloc/com.fayaz07.counter_bloc.MainActivity@97ff458@1[7540])/@0x1b8a50f io.flutter.view.FlutterView{97ff458 VFE...... ........ 0,0-720,1396}
D/SurfaceView( 7540): surfaceCreated 1 #8 io.flutter.view.FlutterView{97ff458 VFE...... ........ 0,0-720,1396}
D/mali_winsys( 7540): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000,  [720x1396]-format:1
D/SurfaceView( 7540): surfaceChanged (720,1396) 1 #8 io.flutter.view.FlutterView{97ff458 VFE...... ........ 0,0-720,1396}
D/ViewRootImpl@f24af35[MainActivity]( 7540): stopped(false) old=false
D/ViewRootImpl@f24af35[MainActivity]( 7540): MSG_RESIZED_REPORT: frame=[0,0][720,1480] ci=[0,42][0,84] vi=[0,42][0,84] or=1
D/ViewRootImpl@f24af35[MainActivity]( 7540): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager( 7540): prepareNavigationBarInfo() DecorView@4f0f7d4[MainActivity]
D/InputMethodManager( 7540): getNavigationBarColor() -855310
D/InputMethodManager( 7540): prepareNavigationBarInfo() DecorView@4f0f7d4[MainActivity]
D/InputMethodManager( 7540): getNavigationBarColor() -855310
V/InputMethodManager( 7540): Starting input: tba=com.fayaz07.counter_bloc ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 7540): startInputInner - Id : 0
I/InputMethodManager( 7540): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 7540): Input channel constructed: fd=100
D/InputTransport( 7540): Input channel destroyed: fd=92

**Comment by fayaz07** [comment]
if you would like to show the dialog, when the widget is initalised, use this code
```dart
void main() => runApp(MaterialApp(home: MyApp()));

  class MyApp extends StatefulWidget {
    @override
    _MyAppState createState() => _MyAppState();
  }

  class _MyAppState extends State<MyApp> {

    ProgressDialog progressDialog;

    @override
    Widget build(BuildContext context) {
      progressDialog = ProgressDialog(context);
      WidgetsBinding.instance.addPostFrameCallback((Duration d){
        progressDialog.show();
      });
      return Scaffold(

      );
    }
  }
```

**Comment by fayaz07** [comment]
> Hello @fayaz07
> 
> please see this repo for the code:
> https://github.com/zmabies/ProgressDialogTest

this didn't give me any issue

**Comment by zmabies** [comment]
> > Hello @fayaz07
> > please see this repo for the code:
> > https://github.com/zmabies/ProgressDialogTest
> 
> this didn't give me any issue

Did you test it with the navigation from home class in main?

**Comment by zmabies** [comment]
> if you would like to show the dialog, when the widget is initalised, use this code
> 
> ```dart
> void main() => runApp(MaterialApp(home: MyApp()));
> 
>   class MyApp extends StatefulWidget {
>     @override
>     _MyAppState createState() => _MyAppState();
>   }
> 
>   class _MyAppState extends State<MyApp> {
> 
>     ProgressDialog progressDialog;
> 
>     @override
>     Widget build(BuildContext context) {
>       progressDialog = ProgressDialog(context);
>       WidgetsBinding.instance.addPostFrameCallback((Duration d){
>         progressDialog.show();
>       });
>       return Scaffold(
> 
>       );
>     }
>   }
> ```

this isn't the issue

**Comment by zmabies** [comment]
Hello @fayaz07, any updates?

**Comment by furkankurt** [comment]
Still same?

**Comment by furkankurt** [comment]
@fayaz07 unfortunately issue isn't resolved. Not always but sometimes I get the error and crash.
`
I/flutter (18088): ProgressDialog shown
E/flutter (18088): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'update' was called on null.
E/flutter (18088): Receiver: null
E/flutter (18088): Tried calling: update()
E/flutter (18088): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (18088): #1      ProgressDialog.update (package:progress_dialog/progress_dialog.dart:83:29)
E/flutter (18088): #2      _EsyaIlaniEkleState.resimYukle.<anonymous closure> (package:ogrencievi/lists/post/post_esya_ilani.dart:465:18)
E/flutter (18088): #3      _rootRun (dart:async/zone.dart:1122:38)
E/flutter (18088): #4      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (18088): #5      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (18088): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (18088): #7      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (18088): #8      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (18088): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter (18088): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (18088): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (18088): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (18088): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (18088): 
`

**Comment by fayaz07** [comment]
Hi everyone, please use await for showing and hiding the dialog just as
```
await pr.show();
... your code
await pr.hide();
```
