### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by brux88** [fayaz07/progress_dialog#3]
i tried , but not work.
show me this error:ackage:pub/src/solver/version_solver.dart  VersionSolver._result
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

pub get failed (1)
exit code 1

**Comment by fayaz07** [comment]
are you facing issues while installing the package @brux88

**Comment by melvinm99** [comment]
Hi, I get an error too when declaring dependency in pubspec. Now I can't paste here the error, I will do it soon. It didn't however compile.

**Comment by fayaz07** [comment]
ok @brux88

**Comment by uzumakinaruto123** [comment]
Here you go

> 
> ...
> Extracting  doc\api\dart-core\Map\keys.html
> Extracting  doc\api\dart-core\Map\length.html
> file doc\api\dart-core\Map\map.html
> already exists. Overwrite with 
> doc\api\dart-core\Map\map.html?
> (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
> ERROR: Can't allocate required memory!
> 
> package:pub/src/io.dart 944:7               _extractTarGzWindows.<fn>
> ===== asynchronous gap ===========================
> package:pub/src/io.dart 821:20              withTempDir
> 
> ===== asynchronous gap ===========================
> 
> package:pub/src/io.dart 915:10              _extractTarGzWindows
> 
> package:pub/src/io.dart 843:18              extractTarGz
> 
> ===== asynchronous gap ===========================
> 
> package:pub/src/source/hosted.dart 302:11   BoundHostedSource._download
> 
> ===== asynchronous gap ===========================
> 
> package:pub/src/source/hosted.dart 196:13   BoundHostedSource.downloadToSystemCache
> 
> ===== asynchronous gap ===========================
> 
> package:pub/src/entrypoint.dart 371:48      Entrypoint._get.<fn>
> 
> ===== asynchronous gap ===========================
> 
> dart:async                                  runZoned
> 
> 
> 
> 
> 
> 
> 
> package:pub/src/http.dart 272:10            withDependencyType
> package:pub/src/entrypoint.dart 367:12      Entrypoint._get
> dart:async                                  Future.wait
> package:pub/src/entrypoint.dart 228:18      Entrypoint.acquireDependencies
> dart:async                                  _completeOnAsyncReturn
> package:pub/src/solver/version_solver.dart  VersionSolver.solve
> dart:async                                  _completeOnAsyncReturn
> package:pub/src/solver/version_solver.dart  VersionSolver._result
> 
> 
> 
> 
> This is an unexpected error. Please run
> 
>     pub --trace --verbosity=warning get --no-precompile
> 
> 
> 
> and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
> pub get failed (1)
> exit code 1

**Comment by melvinm99** [comment]
same error for me

**Comment by fayaz07** [comment]
try
```dart
flutter clean
```
and installing the latest package
