### ISSUE TITLE
Progress Dialog not hidding after API call

### ISSUE THREAD

**Issue by bagus-repository** [fayaz07/progress_dialog#31]
Hey, nice package!
I can not hide the progress dialog after calling my API even isShowing = true,

But when I wrap the progressDialog.hide() with FutureDelayed 3 seconds, the dialog hidden after get my API call.

**Comment by fayaz07** [comment]
hi, sample code please

**Comment by BjoernPetersen** [comment]
I have the same issue. If the API call (or whatever you're indicating the progress of) is too fast, the `hide()` call doesn't actually hide the dialog.

A sample button demonstrating the bug:
```dart
RaisedButton(
  child: Text("Test"),
  onPressed: () {
    final dialog = ProgressDialog(context);
    dialog.style(
      message: 'I\'m here to stay',
    );
    dialog.show();
    // Doing nothing inbetween here...
    // dialog.isShowing() is true
    dialog.hide();
    // dialog.isShowing() is false, but it's still showing
  },
),
```

**Comment by bagus-repository** [comment]
> I have the same issue. If the API call (or whatever you're indicating the progress of) is too fast, the `hide()` call doesn't actually hide the dialog.
> 
> A sample button demonstrating the bug:
> 
> ```dart
> RaisedButton(
>   child: Text("Test"),
>   onPressed: () {
>     final dialog = ProgressDialog(context);
>     dialog.style(
>       message: 'I\'m here to stay',
>     );
>     dialog.show();
>     // Doing nothing inbetween here...
>     // dialog.isShowing() is true
>     dialog.hide();
>     // dialog.isShowing() is false, but it's still showing
>   },
> ),
> ```

Yups in fast condition(show and hide simultaneously the pr not hidden).

I found another issue when defining more progress dialog, the first will always be called whatever progress dialog variable you used;

```dart
@override
  void initState() {
    super.initState();
    progressDialog = new ProgressDialog(context,
        type: ProgressDialogType.Normal, isDismissible: true, showLogs: false)
      ..style(
        message: msg ?? "Memproses...",
        borderRadius: 8.0,
        backgroundColor: Colors.white,
        elevation: 5.0,
        messageTextStyle: TextStyle(fontSize: 16.0),
        // progressWidget: CircularProgressIndicator(),
      );
    progressDownloadDialog = new ProgressDialog(context,
        isDismissible: false, type: ProgressDialogType.Download)
      ..style(
        message: "Mendownload...",
        borderRadius: 8.0,
        backgroundColor: Colors.white,
        elevation: 5.0,
        messageTextStyle: TextStyle(fontSize: 16.0),
        progress: 0.0,
        maxProgress: 100,
        progressTextStyle: TextStyle(
            color: Colors.black, fontSize: 13.0, fontWeight: FontWeight.w400),
      );
  }

**Comment by fayaz07** [comment]
@bagus-repository  how can you access the context widget in initstate, when the package clearly mentions that you need to initialize in the build method

**Comment by BjoernPetersen** [comment]
How is this issue invalid? Just put my sample code in a build method and see for yourself.

**Comment by fayaz07** [comment]
read the rules of the library again @BjoernPetersen

**Comment by BjoernPetersen** [comment]
Are you referring to the "Navigating to next screens must be done after the completion of Future - hide()." part?

**Comment by fernando-s97** [comment]
@BjoernPetersen Did you manage to solve this? I'm facing the same issue

**Comment by fayaz07** [comment]
what issue did you face @fernando-s97 
can you tell me exactly what's the situation?
