### ISSUE TITLE
Getting setState() called in constructor error

### ISSUE THREAD

**Issue by rguntha** [fayaz07/progress_dialog#32]
**Error**
Getting error while calling update function on the Progress dialog object.

**My Code**
                    ProgressDialog pr = new ProgressDialog(context,type: ProgressDialogType.Normal, isDismissible: false);
                    pr.style(message: 'Preparing to create event. Please wait...',progressWidget: CircularProgressIndicator());
                    pr.show();
                    pr.update(message:'Doing final updates. Please wait...');//ERROR Here

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android
 - Version 1.2.0

**Smartphone (please complete the following information):**
 - Device: One plus 3

**Additional context**
E/flutter (14104): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() called in constructor: _BodyState#12216(lifecycle state: created, no widget, not mounted)
E/flutter (14104): This happens when you call setState() on a State object for a widget that hasn't been inserted into the widget tree yet. It is not necessary to call setState() in the constructor, since the state is already assumed to be dirty when it is initially created.
E/flutter (14104): #0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1129
E/flutter (14104): #1      State.setState 
package:flutter/…/widgets/framework.dart:1140
E/flutter (14104): #2      _BodyState.update 
package:progress_dialog/progress_dialog.dart:172
E/flutter (14104): #3      _Body.update 
package:progress_dialog/progress_dialog.dart:161
E/flutter (14104): #4      ProgressDialog.update 
package:progress_dialog/progress_dialog.dart:83
E/flutter (14104): #5      _HazardEventDetailsScreenState.build.<anonymous closure> 
package:mht_flutter/screens/hazard_event_details_screen.dart:185
E/flutter (14104): <asynchronous suspension>
E/flutter (14104): #6      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:654
E/flutter (14104): #7      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:729
E/flutter (14104): #8      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter (14104): #9      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:365
E/flutter (14104): #10     TapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:275
E/flutter (14104): #11     PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:455
E/flutter (14104): #12     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:75
E/flutter (14104): #13     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:102
E/flutter (14104): #14     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:218
E/flutter (14104): #15     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (14104): #16     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter (14104): #17     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter (14104): #18     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (14104): #19     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter (14104): #20     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (14104): #21     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter (14104): #22     _invoke1  (dart:ui/hooks.dart:263:10)
E/flutter (14104): #23     _dispatchPointerDataPacket  (dart:ui/hooks.dart:172:5)
E/flutter (14104):

**Comment by fayaz07** [comment]
Duplicate #30
