### ISSUE TITLE
Progress Dialog Padding 

### ISSUE THREAD

**Issue by viveksakpal** [fayaz07/progress_dialog#33]
Is there a way to add more padding between progressbar and loading text made to make it center.
please revert.

**Comment by fayaz07** [comment]
Hi @viveksakpal , the lib doesn't support that feature as it was designed only to show a progress indicator with some message, I appreciate your need for it in the next update, will allow the users to adjust in a custom way.

**Comment by viveksakpal** [comment]
Thanks for your reply
I really appreciate your help
Great work with the library
Can you please give me the idea how long it can take it will be really
helpful.

**Comment by fayaz07** [comment]
I'm not sure about that

**Comment by fayaz07** [comment]
Please checkout v1.2.2
