### ISSUE TITLE
Progress dialog is not hiding on catchError

### ISSUE THREAD

**Issue by nikhilvc** [fayaz07/progress_dialog#36]
i want to show progress dialog on before of API call .while calling API if there is any error occurred i wants to hide the dialog on CatchError function

**Comment by fayaz07** [comment]
show me the code

**Comment by nikhilvc** [comment]
I handle this issue with blow code

 Future.delayed(Duration(seconds: 3)).then((onValue) {
          if (pr.isShowing())
            pr.hide().whenComplete(() {
              showToast("error");
            });
        });

**Comment by openwrd** [comment]
pr.show();
pr.hide(); //not working

**Comment by nithish-knetworks** [comment]
Not able to close the Dialog.
Source Code:
 ProgressDialog progressDialog = ProgressDialog(context,
                                          type: ProgressDialogType.Normal,isDismissible: true);
                                      progressDialog.style(
                                          message: 'Saving...',
                                          backgroundColor: Colors.white,
                                          progressWidget: CircularProgressIndicator(),
                                          elevation: 10.0,
                                          insetAnimCurve: Curves.easeInOut,
                                          progress: 0.0,
                                          borderRadius: 10.0,
                                          maxProgress: 100.0,
                                          progressTextStyle: TextStyle(
                                              color: Colors.black, fontSize: 13.0, fontWeight: FontWeight.w400),
                                          messageTextStyle: TextStyle(
                                              color: Colors.black, fontSize: 19.0, fontWeight: FontWeight.w600));
                                      progressDialog.show();
                                      //Service layer Call(Async call)
                                      progressDialog.hide();

**Comment by Bahaaib** [comment]
Hi, 
I faced the same issue specifically when any exception has been thrown, i couldn't `dismiss` the progress dialog in any possible way. 
The Solution is: 
inside your catch add `Navigator.of(context).pop();` instead of `progressDialog.dismiss()`.

That works because basically flutter has 2 default routes. The main route which by default renders the Scaffolds and gives them control over the screen. The other is the Modal route which renders over the main route. When a main route tries to render some dialog, it passes the current context to the dialog to take control over the screen. when you dismiss the dialog, you return the context back to the main route. The thing that we've done here.

**Comment by AldiSatrioAji** [comment]
@Bahaaib Been stuck for an hour and finally it's working for me! Thanks

**Comment by rochadaniel** [comment]
After the #41 this code worked for me (handle `.show()` asynchronously):

```dart
ProgressDialog myDialog = ProgressDialog(context, type: ProgressDialogType.Normal);

myDialog.show().then((onValue) {
      myFuture().then((myResult) {
        myDialog.hide();
        
        ...
      }).catchError((onError) {
        myDialog.hide();

        ...
      });
    });
```

**Comment by fayaz07** [comment]
Please use the following code for showing or hiding the progress dialog
```
/// for showing
await pr.show();

/// for hiding
await pr.hide();
```

**Comment by tony123S** [comment]
> Hi,
> I faced the same issue specifically when any exception has been thrown, i couldn't `dismiss` the progress dialog in any possible way.
> The Solution is:
> inside your catch add `Navigator.of(context).pop();` instead of `progressDialog.dismiss()`.
> 
> That works because basically flutter has 2 default routes. The main route which by default renders the Scaffolds and gives them control over the screen. The other is the Modal route which renders over the main route. When a main route tries to render some dialog, it passes the current context to the dialog to take control over the screen. when you dismiss the dialog, you return the context back to the main route. The thing that we've done here.

Well, if I go from page A to page B, in page B catch, I use `Navigator.of(context).pop();` , it dismiss the dialog. But when I back to page A and push to pageB again, it doesn't allow me to go to page B  again because I have `Navigator.of(context).pop();` in catch.
