### ISSUE TITLE
Allow to await for the dialog show

### ISSUE THREAD

**Issue by neokree** [fayaz07/progress_dialog#38]
**Problem statement**
I use the progress dialog to keep the user informed of a blocking operation. 
So the progress dialog must be showed and hidden after an operation, but if the operation is async but terminates very quickly, the dialog is not hidden, because the `showDialog` method (used internally in the `.show()`) does not have finished showing the dialog. 

**Describe the solution you'd like**
I would like to be allow to await the `.show()` method, like this
```
ProgressDialog dialog = ...; 
await dialog.show();

// do some work ...

await dialog.hide();
```

**Comment by openwrd** [comment]
good idea, but  call funciton require **async**.

**Comment by neokree** [comment]
> good idea, but call funciton require **async**.

Yeah sure, it is the main point of doing it.   
Obviously you could also use the `.then()` method and chaining the Futures, but I think it is more readable this way.

**Comment by tmibvishal** [comment]
Until this issue is resolved, you can use
`await Future.delayed(Duration(seconds: 1));`
for allowing the dialog to pop up

**Comment by BjoernPetersen** [comment]
Could we get a new release with the fixed version?

By the way (for the impatient), a workaround until then:

`pubspec.yaml`
```
dependencies:
  progress_dialog:
    git: https://github.com/fayaz07/progress_dialog.git
```

**Comment by fayaz07** [comment]
Update v1.2.1 is live, please checkout
