### ISSUE TITLE
Sample determinate LinearProgressIndicator 

### ISSUE THREAD

**Issue by chitgoks** [fayaz07/progress_dialog#39]
**Is your feature request related to a problem? Please describe.**
This is not a problem. More of a sample code.

**Describe the solution you'd like**
Your sample uses a Circle progress indicator. I hope you can also provide a LinearProgressIndicator that will simulate a determinate progress.

**Describe alternatives you've considered**
Tried to change the widget to linear but it appears beside the message. Would be nice if it is below the message. so an added option will be cool.

**Comment by fayaz07** [comment]
@chitgoks Sure, I will be working on your request, due to busy schedule I wasn't able to focus on it

**Comment by fayaz07** [comment]
Please checkout v1.2.2
