### ISSUE TITLE
Parameter for text align

### ISSUE THREAD

**Issue by nicodumdum** [fayaz07/progress_dialog#42]
I am having issues when I am using some specific strings (e.g. "Updating queue number...") as progress messages where it turns out to be weird looking because of some weird text alignment. (See attached pic)
![Screenshot_20200130-224335](https://user-images.githubusercontent.com/1650987/73460464-7cc95e00-43b3-11ea-9fe7-ee8e2536c49b.png)

I checked the code and it confirmed that it was using justify text alignment.
`Text(_dialogMessage, textAlign: TextAlign.justify, style: _messageStyle)`

I hope you can add an optional parameter for setting the text alignment so I can easily adjust it accordingly.

Thanks! :)

**Comment by fayaz07** [comment]
Thanks @nicodumdum , I will surely look into this issue

**Comment by fayaz07** [comment]
Please checkout latest version v1.2.2, I am closing the issue now, feel free to re-open if it doesn't solve your requirement
