### ISSUE TITLE
Progress dialog is not show when invoke show method.

### ISSUE THREAD

**Issue by liudonghua123** [fayaz07/progress_dialog#44]
**Describe the bug**

**To Reproduce**
I write some code like the following. It is for multi-platform. And the progress dialog is not show in android/web, however the dialog is show in windows platform.

```dart
class IndexPage extends StatefulWidget {
  IndexPage({Key key}) : super(key: key);

  @override
  _IndexPageState createState() => _IndexPageState();
}

// AutomaticKeepAliveClientMixin, see https://blog.csdn.net/a875801/article/details/92829950
// TickerProviderStateMixin, see https://blog.csdn.net/u011272795/article/details/82740389
class _IndexPageState extends State<IndexPage>
    with AutomaticKeepAliveClientMixin, TickerProviderStateMixin {
  List<Course> recommendCourses = [];
  List<Course> freeCourses = [];
  List<News> recommendNews = [];
  ProgressDialog pr;
  TabController _tabController;

  @override
  bool get wantKeepAlive => true;

  @override
  void initState() {
    print('Index, initState');
    pr = new ProgressDialog(context, showLogs: true);
    _tabController = TabController(length: categories.length, vsync: this);
    _updateState();
    super.initState();
  }

  @override
  void dispose() {
    print('Index, dispose');
    _tabController.dispose();
    super.dispose();
  }

  void _updateState() async {
    pr.show();
    print('pr.show()');
    var _recommendCourses = await CommonService().getRecommendCourses(3);
    var _freeCourses = await CommonService().getfreeCourses(2);
    var _recommendNews = await CommonService().getRecommendNews(3);
    print('_updateState: ${_recommendCourses}');
    setState(() {
      print('setState: ${_recommendCourses}');
      recommendCourses = _recommendCourses;
      freeCourses = _freeCourses;
      recommendNews = _recommendNews;
      pr.hide();
      print('pr.hide()');
    });
  }
  //...
}
```

**Expected behavior**
The dialog show as expected.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Chrome 80

**Comment by liudonghua123** [comment]
If I changed `pr.show()` to 
```dart
    WidgetsBinding.instance.addPostFrameCallback((Duration d) {
      pr.show();
    });
```
Then it seems work, I will do more test about this.

**Comment by fayaz07** [comment]
please use ```await pr.show()```
usually in flutter, for the initialization of dialog takes 200 ms

**Comment by liudonghua123** [comment]
@fayaz07 Hi, I tried to `await` it, but it's the same, the dialog is not show.

**Comment by fayaz07** [comment]
thanks @liudonghua123, I will checkit out

**Comment by fayaz07** [comment]
can you post the updated code without the work you include from other files

**Comment by xsahil03x** [comment]
> If I changed `pr.show()` to
> 
> ```dart
>     WidgetsBinding.instance.addPostFrameCallback((Duration d) {
>       pr.show();
>     });
> ```
> 
> Then it seems work, I will do more test about this.

This is because you are trying to show dialog when nothing is rendered on screen. So you need to wait for flutter to render its first screen, then only you can show dialog

**Comment by liudonghua123** [comment]
@fayaz07 @xsahil03x Thanks, because I have deleted those issued code, and I can't reproduce it, I will reopen it if necessary or I can reproduce the issue. Thanks, 😃
