### ISSUE TITLE
Progress gif not showing - v1.2.1

### ISSUE THREAD

**Issue by cardozorobson** [fayaz07/progress_dialog#45]
Hi!! How r u?

The progress gif is not showing, e my log is printing this:
Unable to load asset: packages/progress_dialog/assets/double_ring_loading_io.gif

How i may proceed?

**Comment by fayaz07** [comment]
Hi, I am good, thank you for asking. How are you?

try flutter clean and then flutter packages get and run the app

**Comment by oussamabonnor1** [comment]
Hello, i am using the 1.2.2 version and i had the same issue, @fayaz07 your suggestion works perfectly. Thank you!

**Comment by fayaz07** [comment]
@oussamabonnor1 , good to hear that :)

**Comment by varma017** [comment]
Hello i tried flutter clean and then flutter packages get but its not working for me 
is there any other solution for my problem @fayaz07
