### ISSUE TITLE
Progress dialog with no text

### ISSUE THREAD

**Issue by chitgoks** [fayaz07/progress_dialog#48]
feature request

the progress diañog has no text or label, the width amd height shouñd resize to fit it.

in this case the dialog now becomes a square

**Comment by fayaz07** [comment]
Well, that depends on how you configure your child and there is nothing wrong with the package in making the end result square if you don't decorate it. I am closing this issue as it has nothing wrong with the package and end user should configure it. If you feel there is something wrong, please feel free to re-open the issue
