### ISSUE TITLE
Set Text On Existing Instance

### ISSUE THREAD

**Issue by chitgoks** [fayaz07/progress_dialog#50]
**Is your feature request related to a problem? Please describe.**
Once i have created a progress dialog, there is no way to set the label.

**Describe the solution you'd like**
I am using this dialog to do more than 1 task so a way to be able to change the existing text would be nice.

**Comment by fayaz07** [comment]
@chitgoks , please read the docs first, unnecessarily don't create issues here. There is already a method called update is provided. Go ahead and read docs first.
