### ISSUE TITLE
Has `dismiss()` been replaced from `hide()`?

### ISSUE THREAD

**Issue by enricobenedos** [fayaz07/progress_dialog#51]
I've updated the package version from `v1.1.1` to `1.1.2`. 
This "bug fix" update broke my project because `dismiss()` method does not exist anymore and it is not reported on changelog. Should we use `hide()` now?
Thank you

**Comment by fayaz07** [comment]
Hi @enricobenedos , yeah I actually removed the dismiss method and merged the functionality into ```hide``` method

**Comment by enricobenedos** [comment]
Thank you!
