### ISSUE TITLE
The loading box does not disappear

### ISSUE THREAD

**Issue by lqk9511** [fayaz07/progress_dialog#53]
**Describe the bug**
When I update to the latest version.
If I trigger multiple loading boxes at the same time, I use the `hide()` they will not disappear.
because it has no `dismiss()`.

**To Reproduce**
``` dart
request(BuildContext context) {
  ProgressDialog pr = ProgressDialog(context, type: ProgressDialogType.Normal);
  pr.show();

  // dio ...

  pr.hide();
}
```

**Expected behavior**
Should disappear

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS.13.3.1
 - flutter
Flutter 1.12.13+hotfix.9 • channel stable • git@github.com:flutter/flutter.git
Framework • revision f139b11009 (3 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

**Comment by fayaz07** [comment]
please use the code as 
```
await pr.show();

await pr.hide();
```

**Comment by lqk9511** [comment]
> please use the code as
> 
> ```
> await pr.show();
> 
> await pr.hide();
> ```

I tried that and it still doesn't work. 
When it executes `hide()`, `isShowing()` is `false`,but it is displayed.

**Comment by fernando-s97** [comment]
@lqk9511 Did you manage to solve it? I'm facing the same issue on Android...

**Comment by fayaz07** [comment]
@fernando-s97 what happened like, you are facing all the issues which are present in the issues section?

**Comment by fernando-s97** [comment]
@fayaz07 Yes! The first dialog shows correctly, and the second one never hides, but the isShowing() method returns false

**Comment by fayaz07** [comment]
can you show me the code

**Comment by fernando-s97** [comment]
```dart
await state.progress.fold<Future>(
      () => _downloadDialog.hide(),
      (progress) => _downloadDialog
          .show()
          .then((_) => _downloadDialog.update(progress: progress)),
    );
log('showing: ${_downloadDialog.isShowing()}');
```
