### ISSUE TITLE
Progress Indicator Not Showing

### ISSUE THREAD

**Issue by eniserkaya** [fayaz07/progress_dialog#6]
Hi,

When i use this dialog, there is no progress indicator. The screen only has text. Is there any idea about this issue?

**Comment by fayaz07** [comment]
Hi, we are working on it and we will fix it soon

**Comment by PuneethRegonda** [comment]
The issue is fixed in the latest update 1.0.8

**Comment by fayaz07** [comment]
Thanks @PuneethRegonda
