### ISSUE TITLE
hide method error

### ISSUE THREAD

**Issue by fg2q1q3q** [fayaz07/progress_dialog#7]
I encountered the problem of `hide () `method error reporting in the process of using it.
My code like this：
```
           pr.show();
           UserDao.login( _userName,_password).then((res) {
              pr.hide();
              if (res != null) {
                LocalStorage.save(Config.USER_NAME_KEY, _userName);
                LocalStorage.save(Config.PW_KEY, _password);
                NavigatorUtils.goHome(context);
             }
          });
```
But the error is as follows
```
E/flutter (32311): At this point the state of the widget's element tree is no longer stable. To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
```

**Comment by fayaz07** [comment]
please check if the progress dialog is in showing state or hidden state
```dart
if(pr.isShowing())
  pr.hide();
```

**Comment by fg2q1q3q** [comment]
First of all, the above suggestions didn't help, and I found that` isShowing` is always false by printing logs and viewing source code.

Now I have found the reason for the problem, because every network request I will first determine whether the network is available, if not cancel the request, because this is not a time-consuming operation, which led to the error, you can reproduce this error with the following code：
```           
           pr.show();
           Future.delayed(Duration(seconds: 0)).then((onValue){
              print("pr show? ${pr.isShowing()}");
              pr.hide();
             }
           );
```

1.Whether` seconds` is 0 or 5, `isshowing` is false forever, which is a bug.
2.When `seconds` is 5, it is normal, but when `seconds` is 0, it will report an error. It is suggested to add a rendering completion identifier, cancel the rendering if no rendering is completed when calling `hide`, and call `isShowing` in `hide` for judgment.

**Comment by fayaz07** [comment]
@fg2q1q3q I have got the bug, acutally the isShowing is remaining unchanged on any operation, thanks for reporting. I have fixed the issue, soon I will update the library soon :)

**Comment by fayaz07** [comment]
fixed in the latest version  progress_dialog: ^1.1.0+1

**Comment by fg2q1q3q** [comment]
Thank you. I've tried. Everything's OK.

**Comment by fayaz07** [comment]
@fg2q1q3q :)
