### ISSUE TITLE
Bug on hide

### ISSUE THREAD

**Issue by Lzyct** [fayaz07/progress_dialog#73]
**Describe the bug**
I have issue when try to hide progress dialog.
It's always showing if distance between show and hide is fast

**To Reproduce**
1.show progress dialog
2.try without delay then hide

**Expected behavior**
progress dialog should be hide

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: All

**Comment by fayaz07** [comment]
use await before  show and hide methods

**Comment by Lzyct** [comment]
i was use await when call show and hide method but it's not work @fayaz07 
progressbar not hiding.
Thanks

**Comment by Lzyct** [comment]
![image](https://user-images.githubusercontent.com/1531684/86552373-646cf900-bf7a-11ea-80c5-45ba6606f146.png)

stack in this

**Comment by Lzyct** [comment]
Fix : Need to add delay before hide progress dialog

**Comment by fayaz07** [comment]
No, you wouldn't need to do that, you can just fix it by adding `await` keyword

**Comment by Lzyct** [comment]
not working if just add await,
i was add `await` and still stuck when delay between `.show()` and `.hide()` it's too fast, so i add delay about 300ms before hide
